name: todo_app_tdd_clean_arch
description: A Clean Architecture Todo App with TDD Using Firebase as Remote Data Source and GetStorage as Local Data Source.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  # State Management
  flutter_bloc: ^8.0.1
  # Dependency Injection
  get_it: ^7.2.0
  # Functional Programming
  dartz: ^0.10.1
  # Easy Objects Equality
  equatable: ^2.0.3
  # Internet Connectivity Status
  data_connection_checker_tv: ^0.3.5-nullsafety
  # Local Database
  get_storage: ^2.0.3
  # Firebase Dependencies
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  build_runner: ^2.1.7

flutter:

  uses-material-design: true
